#!/bin/bash

if [ $# -ne 1 ]; then
	echo "	USAGE: $0 filename"
	echo "	Vix is a tool for creating blank bash scripts"
	echo "	very quickly."
	echo "	Vix creates a file with the specified name,"
	echo "	inserts #!/bin/bash at the top and then"
	echo "	adds .sh to the end, makes the file executable"
	echo "	and opens it in vim."
	echo ""
	echo "	Example: $0 myscript"
	echo "	will create an executable \"myscript.sh\" and open"
	echo "	the file with vim."
	echo ""
	exit
fi


echo "#!/bin/bash" >> $1.sh
chmod +x $1.sh
vim $1.sh


